<?php

namespace AppBundle\Repository;

/**
 * Command_StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Command_StateRepository extends \Doctrine\ORM\EntityRepository
{
}
