<?php

namespace AppBundle\Repository;

/**
 * Delivery_AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Delivery_AddressRepository extends \Doctrine\ORM\EntityRepository
{
}
