<?php

namespace AppBundle\Repository;

/**
 * Time_SlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Time_SlotRepository extends \Doctrine\ORM\EntityRepository
{
}
