security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
    firewalls:
        main:
            anonymous: true
            pattern: ^/
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
            logout:
                path:   /logout
                target: login
    access_control:
            - { path: ^/ProductAdd, roles: ROLE_ADMIN }
            - { path: ^/CategoryAdd, roles: ROLE_ADMIN }
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_USER }




#        dev:
 #               pattern: ^/(_(profiler|wdt)|css|images|js)/
  #              security: false
   #     register:
    #                    pattern: ^/register
     #                   security: false
      #  login:
       #         pattern: ^/login$
        #        security: false #}